{
 "title": "MyPanel",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU Panel",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "%ProcessorTime" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_User_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "%UserTime" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "MEM Panel",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "select": [
      [
       { "params": [ "Page_Faults_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "FaultsPerSec" ], "type": "alias" }
      ],
      [
       { "params": [ "Pages_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "PagesPerSec" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "DISK Panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "query": "SELECT mean(\"Percent_Disk_Read_Time\") AS \"%ReadTime\", mean(\"Percent_Disk_Write_Time\") AS \"%WriteTime\" FROM \"win_disk\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "Percent_Disk_Read_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "%ReadTime" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_Disk_Write_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "%WriteTime" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}